name: pocket_financier_proj
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  equatable: ^2.0.5
  flagsmith: ^6.0.0
  flutter:
    sdk: flutter
  flutter_app_info: ^3.0.2
  flutter_bloc: ^8.1.6
  flutter_email_sender: ^6.0.3
  flutter_launcher_icons: ^0.14.1
  #  flutter_native_splash: ^2.4.3
  flutter_svg: ^2.0.14
  in_app_review: ^2.0.9
  flutter_screenutil: ^5.9.3
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs:
    git:
      url: https://github.com/MrLittleWhite/isar_flutter_libs.git
  path_provider: ^2.1.5
  cupertino_icons: ^1.0.8
  blur: ^4.0.0
  dio: ^5.7.0
  pull_down_button: ^0.10.2
  fl_chart: ^0.70.2
  flutter_spinkit: ^5.2.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  lint: ^2.3.0

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: 'Quicksand'
      fonts:
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
    - family: 'Nunito'
      fonts:
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/Logo.png"